name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (optional)'
        required: false
        default: ''
      run_id:
        description: 'GitHub Actions Run ID (optional)'
        required: false
        default: ''

jobs:
  create-release:
    if: github.repository == 'DIRACGrid/DIRACOS2'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        uses: conda-incubator/setup-miniconda@master
        with:
          environment-file: scripts/environment.yml
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: Create release
        run: |
          scripts/make_release.py \
            --token="${{ secrets.GITHUB_TOKEN }}" \
            --run-id="${{ github.event.inputs.run_id }}" \
            --version="${{ github.event.inputs.version }}" \
            --make-release
